# Implementing the Multivariable-Linear Regression

In [9]:
import numpy as np
import matplotlib.pyplot as ply
import seaborn as sns 

<a name="toc_15456_2"></a>

You will use the motivating example of housing price prediction. The training dataset contains three examples with four features (size, bedrooms, floors and, age) shown in the table below.  Note that, unlike the earlier labs, size is in sqft rather than 1000 sqft. This causes an issue, which you will solve in the next lab!

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           |  

You will build a linear regression model using these values so you can then predict the price for other houses. For example, a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old.  

Please run the following code cell to create your `X_train` and `y_train` variables.

In [10]:
X_train=np.array([[2104,5,1,45],  # Training Set Number -1
                 [1416,3,2,40], # Training set Number -2 
                 [852,2,1,35]])  # Training set Number -3
 
Y_train=np.array([460,232,178])
#  We have to treat the Whole Operation Like Two-Dimensional Array i and j 
print(X_train[1,2]) # Operations of 2-Dimensional Arrays 

2


In [11]:
# Defining the compute_function 
def compute_function(x,w,b):
    f_wb=np.dot(x,w) +b
    return f_wb

It is important to note that here the parameter `x` and `w `passed represents Vectors 

In [12]:
# Defining the compute_cost
def compute_cost(x,y,w,b):
    m=x.shape[0]
    cost=0.0
    for i in range(m):
        temp_i=((np.dot(x[i],w)+b)-y[i])**2
        cost += temp_i
    cost = cost/(2*m)
    return cost

Important Point (Added whole code for all three functions to the notebook) :
for j in range(n):                         
            `dj_dw[j] = dj_dw[j] + err * X[i, j]`    

In [13]:
#  Calculating the Derivatives Vector 
def gradient_cal(x,y,w,b):
# df_dw --> Will be a vector 
# df_db --> will be a number (floating point )

# X_train= [[2104,5,1,45](i=0),[1416,3,2,40](i=1), [852,2,1,35](i=2)]
# m=3
# n=4
# w = [w1 w2 w3 w4]
# y = [y1 y2 y3 ]


    df_db=0.0 
    n=x.shape[1]
    m=x.shape[0]
    df_dw=np.zeros((n,))   # Initializing the List with required size to avoid the error

    for i in range(m):
        common_part = (compute_function(x[i],w,b) -y[i])
        for j in range(n):
            df_dw[j]+=common_part*x[i,j]  # This denotes an Element not any other thing
        df_db += common_part
        
    df_dw=df_dw/m
    df_db=df_db/m

    return df_dw,df_db

In [28]:
# Implementing the Gradient Descent Algorithm
def descent_algo(x,y,learning_rate,iterations):

    m=x.shape[0]
    n=x.shape[1]
    w_init = np.array([0,0,0,0])
    b_init=0.0

    for i in range(iterations):
        dj_dw,dj_db=gradient_cal(x,y,w_init,b_init)
        temp_w=w_init - (learning_rate * dj_dw)
        temp_b=b_init - (learning_rate * dj_db)
        w_init=temp_w # Here we are updating a list and not any single variable 
        b_init=b_init
   
    return w_init,b_init

# Predicting the Values using the gradient Descent Models



In [23]:
print(f"The Optimized Values for W(weight): {descent_algo(X_train,Y_train,0.001,10000)[0]} The Optimised Value for b(bias) : {descent_algo(X_train,Y_train,0.001,10000)[1]}")

C:\Users\Sian\AppData\Local\Temp\ipykernel_22020\790436643.py:21: RuntimeWarning: overflow encountered in scalar multiply
  df_dw[j]+=common_part*x[i,j]  # This denotes an Element not any other thing
C:\Users\Sian\AppData\Local\Temp\ipykernel_22020\2342113286.py:11: RuntimeWarning: invalid value encountered in subtract
  temp_w=w_init - (learning_rate * dj_dw)


The Optimized Values for W(weight): [nan nan nan nan] The Optimised Value for b(bias) : 0.0


In [8]:
print(gradient_cal(X_train,Y_train,np.array([1,2,3,4]),34)[0])
print(descent_algo(X_train,Y_train,0.001,1000)[0])

[2.21109467e+06 5.07833333e+03 1.83533333e+03 5.65733333e+04]
[nan nan nan nan]


C:\Users\Sian\AppData\Local\Temp\ipykernel_22020\2292124465.py:21: RuntimeWarning: overflow encountered in scalar multiply
  df_dw[j]+=common_part*x[i,j]  # This denotes an Element not any other thing
C:\Users\Sian\AppData\Local\Temp\ipykernel_22020\3887814363.py:11: RuntimeWarning: invalid value encountered in subtract
  temp_w=w_init- (learning_rate * dj_dw)


In [27]:
print(Y_train)

[460 232 178]


In [24]:
print(gradient_cal(X_train,Y_train,np.zeros(4),3))  # Method has no problems at all

(array([-4.78297333e+05, -1.10733333e+03, -3.63333333e+02, -1.19500000e+04]), np.float64(-287.0))


In [35]:
w_opt,b_opt=descent_algo(X_train,Y_train,0.01,20)
print(w_opt)
print(b_opt)

[-7.31298777e+86 -1.68291368e+84 -5.91385887e+83 -1.85074783e+85]
0.0


In [44]:
# Probelm while running the Algorith for more than 100 iterations
w_opt,b_opt=descent_algo(X_train,Y_train,0.0000005,1000)
print(w_opt)
print(b_opt)

[ 0.20396437  0.0037492  -0.01124879 -0.06586307]
0.0


# There is a issue when I keep the learning rate equal to = 0.1 and iterations are more than 100
# But when learning rate is 0.0000005 and i keep iterations = 10000 eveything seems to work fine